# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.5 PHPCS_TEST=1
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Update and validate composer configuration
  - composer self-update || true
  - composer clear-cache
  - composer validate --strict

  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit silverstripe-composer-update-checker/tests
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs silverstripe-composer-update-checker/src silverstripe-composer-update-checker/tests; fi
